import torch
import torch.nn as nn
import torch.nn.functional as F
import math
import warnings
import random
import numpy as np
from collections import OrderedDict
from .drop import DropPath
# from utils import trunc_normal_


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)



class MLP(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x


class SpatialAttention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        qk_dim = dim // num_heads

        self.scale = qk_scale or qk_dim ** -0.5

        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)   # (B, J, C) -> (B, J, 3C)
        self.proj_drop = nn.Dropout(proj_drop)


    def forward(self, x, seqlen=1):
        B, J, C = x.shape
        
        # (B, J, C) -> (B, J, 3C) -> (B, J, 3, #heads, C//#heads) -> (3, B, #heads, J, C//#heads)
        qkv = self.qkv(x).reshape(B, J, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        
        q, k, v = qkv[0], qkv[1], qkv[2]    # (B, #heads, J, C//#heads)
        x = self.forward_spatial(q, k, v)

        x = self.proj(x)
        x = self.proj_drop(x)

        return x


    def forward_spatial(self, q, k, v):
        B, _, J, Chead = q.shape        # (B, #heads, J, C//#heads)
        # (B, #heads, J, C//#heads) @ (B, #heads, C//#heads, J) -> B, #heads, J, J
        attn = (q @ k.transpose(-2, -1)) * self.scale   
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)
        # (B, #heads, J, J) @ (B, #heads, J, C//#heads) -> B, #heads, J, C//#head
        x = attn @ v    
        # (B, #heads, J, C//#head) -> (B, J, #heads, C//#head) -> (B, J, C)
        x = x.transpose(1,2).reshape(B, J, Chead*self.num_heads)    # B, J, Chead*#heads
        return x



class SpatialBlock(nn.Module):

    def __init__(self, dim, num_heads, mlp_ratio=4., mlp_out_ratio=1., qkv_bias=True, qk_scale=None, 
                    drop=0., attn_drop=0., drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()

        self.norm1_s = norm_layer(dim)
        self.attn_s = SpatialAttention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)

        
        # NOTE: drop path for stochastic depth, we shall see if this is better than dropout here
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        
        self.norm2_s = norm_layer(dim)

        mlp_hidden_dim = int(dim * mlp_ratio)
        mlp_out_dim = int(dim * mlp_out_ratio)
        self.mlp_s = MLP(in_features=dim, hidden_features=mlp_hidden_dim, out_features=mlp_out_dim, 
                            act_layer=act_layer, drop=drop)


    def forward(self, x, seqlen=1):

        x = x + self.drop_path(self.attn_s(self.norm1_s(x), seqlen))
        x = x + self.drop_path(self.mlp_s(self.norm2_s(x)))

        return x

class SkeleEmbed(nn.Module):
    """Image to Patch Embedding"""

    def __init__(
        self,
        dim_in=3,
        dim_feat=256,
        num_frames=100,
        num_joints=25,
        patch_size=1,
        t_patch_size=4,
    ):
        super().__init__()
        assert num_frames % t_patch_size == 0
        num_patches = (
            (num_joints // patch_size) * (num_frames // t_patch_size)
        )

        self.num_joints = num_joints
        self.patch_size = patch_size

        self.num_frames = num_frames
        self.t_patch_size = t_patch_size

        self.num_patches = num_patches

        kernel_size = [t_patch_size, patch_size]
        self.proj = nn.Conv2d(dim_in, dim_feat, kernel_size=kernel_size, stride=kernel_size)

    def forward(self, x):
        _, T, V, _ = x.shape
        x = torch.einsum("ntsc->ncts", x)  # [N, C, T, V]
        
        x = self.proj(x)
        x = torch.einsum("ncts->ntsc", x)  # [N, T, V, C]
        return x


class SpatialFormer(nn.Module):
    def __init__(self, dim_in=3, dim_feat=256, 
                 depth=5, num_heads=8, mlp_ratio=4, 
                 num_frames=100, num_joints=25, patch_size=1, t_patch_size=4,
                 qkv_bias=True, qk_scale=None, drop_rate=0., attn_drop_rate=0., 
                 drop_path_rate=0., norm_layer=nn.LayerNorm, norm_skes_loss=False):
        super().__init__()

        self.dim_feat = dim_feat

        self.num_joints = num_joints
        self.num_frames = num_frames
        self.patch_size = patch_size
        self.t_patch_size = t_patch_size

        # self.joints_embed = nn.Linear(dim_in, dim_feat)
        self.joints_embed = nn.Linear(dim_in*patch_size*t_patch_size, dim_feat)
        # self.joints_embed = SkeleEmbed(dim_in, dim_feat, num_frames, num_joints, patch_size, t_patch_size)
        self.pos_drop = nn.Dropout(p=drop_rate)
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks_s = nn.ModuleList([
            SpatialBlock(
                dim=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer
                )
            for i in range(depth)])

        self.pos_embed = nn.Parameter(torch.zeros(1, num_joints, dim_feat))
        trunc_normal_(self.pos_embed, std=.02)

        self.norm = norm_layer(dim_feat)

        self.apply(self._init_weights)      


    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)  
        
    def forward(self, x):   
        B, F, J, C = x.shape
        x = self.joints_embed(x)
        _, Fp, Jp, _ = x.shape
        x = x.reshape(-1, Jp, self.dim_feat)     # BF, J, C
        x = x + self.pos_embed[:, :Jp, :]      # BF, J, dim_feat
        x = self.pos_drop(x)

        for idx, blk_s in enumerate(self.blocks_s):
            x_s = blk_s(x, Fp)
            x = x_s

        x = self.norm(x)
        x = x.reshape(B, Fp, Jp, -1)
        return x


class SpatialFormerUnpatch(nn.Module):
    def __init__(self, dim_in=3, dim_feat=256, 
                 depth=5, num_heads=8, mlp_ratio=4, 
                 num_frames=100, num_joints=25, patch_size=1, t_patch_size=4,
                 qkv_bias=True, qk_scale=None, drop_rate=0., attn_drop_rate=0., 
                 drop_path_rate=0., norm_layer=nn.LayerNorm, norm_skes_loss=False):
        super().__init__()

        self.dim_feat = dim_feat

        self.num_joints = num_joints
        self.num_frames = num_frames
        self.patch_size = patch_size
        self.t_patch_size = t_patch_size

        self.joints_embed = nn.Linear(dim_in, dim_feat)
        # self.joints_embed = nn.Linear(dim_in*patch_size*t_patch_size, dim_feat)
        # self.joints_embed = SkeleEmbed(dim_in, dim_feat, num_frames, num_joints, patch_size, t_patch_size)
        self.pos_drop = nn.Dropout(p=drop_rate)
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks_s = nn.ModuleList([
            SpatialBlock(
                dim=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer
                )
            for i in range(depth)])

        self.pos_embed = nn.Parameter(torch.zeros(1, num_joints, dim_feat))
        trunc_normal_(self.pos_embed, std=.02)

        self.norm = norm_layer(dim_feat)

        self.apply(self._init_weights)      


    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)  
        
    def forward(self, x):   
        B, F, J, C = x.shape
        x = self.joints_embed(x)
        _, Fp, Jp, _ = x.shape
        x = x.reshape(-1, Jp, self.dim_feat)     # BF, J, C
        x = x + self.pos_embed[:, :Jp, :]      # BF, J, dim_feat
        x = self.pos_drop(x)

        for idx, blk_s in enumerate(self.blocks_s):
            x_s = blk_s(x, Fp)
            x = x_s

        x = self.norm(x)
        x = x.reshape(B, Fp, Jp, -1)
        return x

class TemporalAttention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        qk_dim = dim // num_heads

        self.scale = qk_scale or qk_dim ** -0.5

        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)   # (B, T, C) -> (B, T, 3C)
        self.proj_drop = nn.Dropout(proj_drop)


    def forward(self, x, seqlen=8):
        B, T, C = x.shape
        # (B, T, C) -> (B, T, 3C) -> (B, T, 3, #heads, C//#heads) -> (3, B, #heads, T, C//#heads)
        qkv = self.qkv(x).reshape(B, T, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        
        q, k, v = qkv[0], qkv[1], qkv[2]    # (B, #heads, T, C//#heads)
        x = self.forward_temporal(q, k, v, seqlen)

        x = self.proj(x)
        x = self.proj_drop(x)

        return x


    def forward_temporal(self, q, k, v, seqlen=8):
        B, _, T, Chead = q.shape    # (B, #heads, T, C//#heads)
        # (B, #heads, seqlen, T//seqlen, C//#heads) -> (B, #heads, T//seqlen, seqlen, C//#heads)
        qt = q.reshape(B, self.num_heads, seqlen, -1, Chead).permute(0, 1, 3, 2, 4) # B, #heads, T//seqlen, seqlen, Chead
        kt = k.reshape(B, self.num_heads, seqlen, -1, Chead).permute(0, 1, 3, 2, 4) 
        vt = v.reshape(B, self.num_heads, seqlen, -1, Chead).permute(0, 1, 3, 2, 4) 

        # (B, #heads, T//seqlen, seqlen, Chead) @ (B, #heads, T//seqlen, Chead, seqlen)
        attn = (qt @ kt.transpose(-2, -1)) * self.scale # B, #heads, T//seqlen, seqlen, seqlen
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = attn @ vt   # B, #heads, T//seqlen, seqlen, C//#head
        # B, #heads, T//seqlen, seqlen, C//#head -> B, seqlen, T//seqlen, #heads, C//#heads
        x = x.permute(0, 3, 2, 1, 4).reshape(B, T, Chead*self.num_heads)    # B, T, Chead*#heads
        return x



class TemporalBlock(nn.Module):

    def __init__(self, dim, num_heads, mlp_ratio=4., mlp_out_ratio=1., qkv_bias=True, qk_scale=None, 
                    drop=0., attn_drop=0., drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()

        self.norm1_t = norm_layer(dim)
        self.attn_t = TemporalAttention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale, attn_drop=attn_drop, proj_drop=drop)

        # NOTE: drop path for stochastic depth, we shall see if this is better than dropout here
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        
        self.norm2_t = norm_layer(dim)

        mlp_hidden_dim = int(dim * mlp_ratio)
        mlp_out_dim = int(dim * mlp_out_ratio)
        self.mlp_t = MLP(in_features=dim, hidden_features=mlp_hidden_dim, out_features=mlp_out_dim, 
                            act_layer=act_layer, drop=drop)


    def forward(self, x, seqlen=8):

        x = x + self.drop_path(self.attn_t(self.norm1_t(x), seqlen))
        x = x + self.drop_path(self.mlp_t(self.norm2_t(x)))

        return x


class TemporalFormer(nn.Module):
    def __init__(self, dim_in=3, dim_feat=256,
                 depth=5, num_heads=8, mlp_ratio=4, 
                 num_frames=100, num_joints=25, patch_size=1, t_patch_size=4,
                 qkv_bias=True, qk_scale=None, drop_rate=0., attn_drop_rate=0.,
                 drop_path_rate=0., norm_layer=nn.LayerNorm, norm_skes_loss=False):
        super().__init__()

        self.dim_feat = dim_feat

        self.num_joints = num_joints
        self.num_frames = num_frames
        self.patch_size = patch_size
        self.t_patch_size = t_patch_size
        
        # self.temp_embed = nn.Linear(dim_in, dim_feat)
        self.temp_embed = nn.Linear(dim_in*patch_size*t_patch_size, dim_feat)
        self.temp_drop = nn.Dropout(p=drop_rate)
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)] # stochastic depth decay rule
        self.blocks_t = nn.ModuleList([
            TemporalBlock(
                dim=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, norm_layer=norm_layer
                )
            for i in range(depth)])

        self.time_embed = nn.Parameter(torch.zeros(1, num_frames, dim_feat))
        trunc_normal_(self.time_embed, std=.02)

        self.norm = norm_layer(dim_feat) 

        self.apply(self._init_weights)


    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    
    def forward(self, x):   
        B, F, J, C = x.shape
        x = x.permute(0, 2, 1, 3).reshape(-1, F, C)     # BJ, F, C
        x = self.temp_embed(x)    # BJ, F, dim_feat
        x = x + self.time_embed[:, :F, :]      # BJ, F, dim_feat
        x = self.temp_drop(x)

        for idx, blk_t in enumerate(self.blocks_t):
            x_t = blk_t(x, F)
            x = x_t

        x = self.norm(x)
        x = x.reshape(B, J, F, -1).permute(0, 2, 1, 3)

        return x

    
class Predictor(nn.Module):
    def __init__(self, dim_in=256, dim_feat=256, 
                 depth=3, num_heads=8, mlp_ratio=4, 
                 num_frames=100, num_joints=25,
                 qkv_bias=True, qk_scale=None, drop_rate=0., attn_drop_rate=0., 
                 drop_path_rate=0., norm_layer=nn.LayerNorm, norm_skes_loss=False):
        super().__init__()

        self.dim_feat = dim_feat
        self.decoder_embed = nn.Linear(dim_feat, dim_feat, bias=True)
        self.pos_drop = nn.Dropout(p=drop_rate)
        self.temp_drop = nn.Dropout(p=drop_rate)
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)] # stochastic depth decay rule
        self.blocks_s = nn.ModuleList([
            SpatialBlock(
                dim=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, norm_layer=norm_layer
                )
            for i in range(depth)])

        self.pos_embed = nn.Parameter(torch.zeros(1, 1, num_joints, dim_feat))
        self.time_embed = nn.Parameter(torch.zeros(1, num_frames, 1, dim_feat))
        trunc_normal_(self.pos_embed, std=.02)
        trunc_normal_(self.time_embed, std=.02)
        
        self.norm = norm_layer(dim_feat)

        self.apply(self._init_weights)
    

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)


    def forward(self, x):   
        B, F, J, C = x.shape
        x = self.decoder_embed(x)
        x = x + self.pos_embed[:, :, :J, :]      # B, F, J, dim_feat
        x = x + self.time_embed[:, :F, :, :]      # B, F, J, dim_feat
        
        x = x.reshape(-1, F*J, C)     # B, F * J, C
        B = x.shape[0]

        for idx, blk_s in enumerate(self.blocks_s):
            x_s = blk_s(x, F)
            x = x_s

        x = self.norm(x)
        x = x.reshape(B, F, J, -1)

        return x



class Decoder(nn.Module):
    def __init__(self, dim_in=256, dim_feat=256, 
                 depth=3, num_heads=8, mlp_ratio=4, 
                 num_frames=100, num_joints=25, patch_size=1, t_patch_size=4,
                 qkv_bias=True, qk_scale=None, drop_rate=0., attn_drop_rate=0., 
                 drop_path_rate=0., norm_layer=nn.LayerNorm, norm_skes_loss=False):
        super().__init__()

        self.dim_feat = dim_feat
        self.decoder_embed = nn.Linear(dim_feat, dim_feat, bias=True)
        self.pos_drop = nn.Dropout(p=drop_rate)
        self.temp_drop = nn.Dropout(p=drop_rate)
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)] # stochastic depth decay rule
        self.blocks_s = nn.ModuleList([
            SpatialBlock(
                dim=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, norm_layer=norm_layer
                )
            for i in range(depth)])

        self.pos_embed = nn.Parameter(torch.zeros(1, 1, num_joints, dim_feat))
        self.time_embed = nn.Parameter(torch.zeros(1, num_frames, 1, dim_feat))
        trunc_normal_(self.pos_embed, std=.02)
        trunc_normal_(self.time_embed, std=.02)
        
        self.norm = norm_layer(dim_feat)

        self.apply(self._init_weights)
    

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)


    def forward(self, x):   
        B, F, J, C = x.shape
        x = self.decoder_embed(x)
        x = x + self.pos_embed[:, :, :J, :]      # B, F, J, dim_feat
        x = x + self.time_embed[:, :F, :, :]      # B, F, J, dim_feat
        
        x = x.reshape(-1, F*J, C)     # B, F * J, C
        B = x.shape[0]

        for idx, blk_s in enumerate(self.blocks_s):
            x_s = blk_s(x, F)
            x = x_s

        x = self.norm(x)
        x = x.reshape(B, F, J, -1)

        return x


class ActionHeadLinprobe(nn.Module):
    def __init__(self, dim_feat=512, num_classes=60, num_joints=25):
        super(ActionHeadLinprobe, self).__init__()
        self.fc = nn.Linear(dim_feat, num_classes)
        
    def forward(self, feat):
        '''
            Input: (N, M, T, J, C)
        '''
        N, M, T, J, C = feat.shape
        feat = feat.mean(dim=[1,2,3])
        feat = self.fc(feat)
        return feat

class ActionHeadFinetune(nn.Module):
    def __init__(self, dropout_ratio=0., dim_feat=256, num_classes=60, num_joints=25, hidden_dim=2048):
        super(ActionHeadFinetune, self).__init__()
        self.dropout = nn.Dropout(p=dropout_ratio)
        self.bn = nn.BatchNorm1d(hidden_dim, momentum=0.1)
        self.relu = nn.ReLU(inplace=True)
        self.fc1 = nn.Linear(dim_feat*num_joints, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, num_classes)
        
    def forward(self, feat):
        '''
            Input: (N, M, T, J, C)
        '''
        N, M, T, J, C = feat.shape
        feat = self.dropout(feat)
        feat = feat.permute(0, 1, 3, 4, 2)      # (N, M, T, J, C) -> (N, M, J, C, T)
        feat = feat.mean(dim=-1)
        feat = feat.reshape(N, M, -1)           # (N, M, J*C)
        feat = feat.mean(dim=1)
        feat = self.fc1(feat)
        feat = self.bn(feat)
        feat = self.relu(feat)    
        feat = self.fc2(feat)
        return feat



class VanillaFormer(nn.Module):
    def __init__(self, dim_in=3, dim_feat=256, 
                 depth=5, num_heads=8, mlp_ratio=4, 
                 num_frames=100, num_joints=25, patch_size=1, t_patch_size=4,
                 qkv_bias=True, qk_scale=None, drop_rate=0., attn_drop_rate=0., 
                 drop_path_rate=0., norm_layer=nn.LayerNorm, norm_skes_loss=False):
        super().__init__()

        self.dim_feat = dim_feat

        self.num_joints = num_joints
        self.num_frames = num_frames
        self.patch_size = patch_size
        self.t_patch_size = t_patch_size

        self.joints_embed = nn.Linear(dim_in, dim_feat)
        # self.joints_embed = SkeleEmbed(dim_in, dim_feat, num_frames, num_joints, patch_size, t_patch_size)
        self.pos_drop = nn.Dropout(p=drop_rate)
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
        self.blocks_s = nn.ModuleList([
            SpatialBlock(
                dim=dim_feat, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale,
                drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer
                )
            for i in range(depth)])


        self.pos_embed = nn.Parameter(torch.zeros(1, 1, num_joints, dim_feat))
        self.time_embed = nn.Parameter(torch.zeros(1, num_frames, 1, dim_feat))
        trunc_normal_(self.pos_embed, std=.02)
        trunc_normal_(self.time_embed, std=.02)

        self.norm = norm_layer(dim_feat)

        self.apply(self._init_weights)      


    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            # we use xavier_uniform following official JAX ViT:
            torch.nn.init.xavier_uniform_(m.weight)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)  
        
    def forward(self, x):   
        B, F, J, C = x.shape
        x = self.joints_embed(x)
        x = x + self.pos_embed[:, :, :J, :]      # B, F, J, dim_feat
        x = x + self.time_embed[:, :F, :, :]      # B, F, J, dim_feat
        
        x = x.reshape(-1, F*J, self.dim_feat)     # B, F * J, C
        B = x.shape[0]

        for idx, blk_s in enumerate(self.blocks_s):
            x_s = blk_s(x, F)
            x = x_s

        x = self.norm(x)
        x = x.reshape(B, F, J, -1)

        return x