# data
feeder: feeder.feeder_ntu.Feeder
train_feeder_args:
  data_path: dataset/NTU60/NTU60_XSub_kf.npz
  split: train
  use_mmap: True
  random_choose: False
  random_shift: False
  random_move: True
  random_spatial_flip: True
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

# model
model: models.models_v1.TeacherStudentNetwork
model_args:
  dim_in: 3
  dim_feat: 256
  depth: 8
  pred_depth: 5
  decoder_depth: 5
  num_heads: 8
  mlp_ratio: 4
  num_frames: 120
  num_joints: 25
  patch_size: 1
  t_patch_size: 4
  qkv_bias: True
  qk_scale: NULL
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.
  alpha: 0.9999
  mode: parallel

# training
epochs: 400
warmup_epochs: 20
batch_size: 80
num_workers: 8
lr: 1e-3
min_lr: 5e-4
weight_decay: 0.05
mask_ratio: 0.5
motion_stride: 1
motion_aware_tau: 0.80
norm_skes_loss: True

output_dir: ./output_dir_parallel_1
log_dir: ./output_dir_parallel_1
resume: ./output_dir_parallel_1/checkpoint-latest.pth
balanceLoss: False
debug: False